version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend_app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8090:8090"
    env_file:
        - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: