version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "8090:8090"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  caddy:
    image: caddy:latest
    container_name: caddy_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - postgres

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
